### ISSUE TITLE
data-type="image" ignored

### ISSUE THREAD

**Issue by kajusK** [trvswgnr/bs5-lightbox#6]
When I try to force data type (image with extension unknown to the lightbox - JPG in capitals) by `data-type="image"`, the lightbox is forced to be rendered in an iframe, causing incorrect image alignment.

Basically I'm trying to do the same as mentioned in https://trvswgnr.github.io/bs5-lightbox/#force-type, but the option is ignored (this happens also in the linked example).

**Comment by djonik1562** [comment]
I have same problem.
![2022-01-24_10-44-49](https://user-images.githubusercontent.com/29034883/150743806-989d5f0c-9f78-4be3-bc2a-a1e592129ae0.png)

**Comment by trvswgnr** [comment]
Thanks for bringing this to my attention, I'll try to recreate ASAP.

**Comment by mihakot** [comment]
@trvswgnr 
Perhaps if you bring the file name with the extension to lowercase and check it, then the problem will disappear.

**Comment by georgegoudie** [comment]
Yeo data-type seems to be completely ignored

**Comment by trvswgnr** [comment]
This issue has been fixed in [v1.7.9](https://github.com/trvswgnr/bs5-lightbox/releases/tag/v1.7.9)

**Comment by hovi** [comment]
Hi,

just came across the same issue. I tried it with 1.7.9, 1.7.10 and still facing the same problem.
Also I couldn't find non-minified .js bundle. Would be helpful to provide that - it would make it easier for me to debug without setting up the project.

**Comment by trvswgnr** [comment]
@hovi can you provide an example of your code? It seems to be working as expected in the documentation example. I’ll add a non-minified bundle in the next release.

**Comment by hovi** [comment]
@trvswgnr you can see it here:
https://www.honor.cz/en/detail/3779/
Or choose any other from the list:
https://www.honor.cz/en/nase-nabidka/

**Comment by trvswgnr** [comment]
@hovi added fix in [v1.7.11](https://github.com/trvswgnr/bs5-lightbox/releases/tag/v1.7.11). You also shouldn't need to force type on urls with '.JPG', since check for supported image types is now case-insensitive.

**Comment by hovi** [comment]
Very good. I updated the version and it's fine now, thanks. You didn't add non-minified bundle though.
